"""
Django settings for m_apartment_api project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import django_heroku
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&*$i-c92(*wc5+er^v23!0_^%sbuae_s+gl%x#p01ud#7^4-vx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

import pymysql

pymysql.install_as_MySQLdb()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apartment',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
    'corsheaders'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

CKEDITOR_UPLOAD_PATH = "ckeditors/images/"

AUTH_USER_MODEL = 'apartment.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'm_apartment_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'm_apartment_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'apartment_db',
        'USER': 'root',
        'PASSWORD': 'Liemkute03',
        'HOST': ''  # mặc định localhost
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'tnminhliem03$apartmentdb',
        # # 'NAME': 'apartment_manager_db_test',
        # 'USER': 'tnminhliem03',
        # 'PASSWORD': 'Liemkute03',
        # 'HOST': 'tnminhliem03.mysql.pythonanywhere-services.com'  # mặc định localhost
    }
}

import cloudinary

cloudinary.config(
    cloud_name="dr1frcopo",
    api_key="388823961895246",
    api_secret="5MZV45WmN3WZOIurHEL6r3euMvI"
)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
django_heroku.settings(locals())

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Local
CLIENT_ID = '4WQgo6OG13j1Ca5YAD7VzIRZrN0hvGtMx4Upbsy8'
CLIENT_SECRET = 'oMdZge49c15Q5d6QquDQceKhqxrrVb61AJtOknPKh6RaSxl40atL5KnOePvj7yzXHxvmmAyULBS2vNJ3z5OcXVKxTmbcmfBsJ3pvtiwceXbQ8VVHHT2y4dZA7SMnzEjr'

# Pythonanywhere
CLIENT_ID = 'ixf3r8dG1ckyj2LGi9UQrLhu9cSU8cNyPIDsURrS'
CLIENT_SECRET = '5EECr7BSNWYN5oaQv6h9fyAfMOFiXcaMd5TvX0DvD0nXCujsiE4SajgkjLHMpERz2VIEYUniJJQtBx6K0COIYctCSYNeMMTHquCyuXYKZEhorV1lhbMOxgYRH82VLamU'
OAUTH2_PROVIDER = {'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore'}

# vnpay
VNPAY_RETURN_URL = 'http://127.0.0.1:8000/paid'
VNPAY_PAYMENT_URL = 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'
VNPAY_API_URL = 'https://sandbox.vnpayment.vn/merchant_webapi/api/transaction'
VNPAY_TMN_CODE = 'BBJDENSU'
VNPAY_HASH_SECRET_KEY = '1S8CJ30B6CNNK2G4I2A0GJ6RYKEQN966'

# momo
MOMO_PARTNER_CODE = "MOMO"
MOMO_ACCESS_KEY = "F8BBA842ECF85"
MOMO_SECRET_KEY = "K951B6PE1waDMi640xX08PD3vg6EkVlz"
MOMO_RETURN_URL = "http://127.0.0.1:8000/paid"

# Mailjet
MAILJET_API_KEY = "8f7dcc3fe8215b23854980d5cb277cb2"
MAILJET_SECRET_KEY = "2415f517faefb7eb775ec60e4a498e4b"
MAILJET_EMAIL_SENDER = "liem.tnm@gmail.com"
MAILJET_EMAIL_TARGET = "trannguyenminhliem181203@gmail.com"
